# Generated by Django 4.2.30 on 2026-05-27 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(db_column='ativo', default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_column='data_criacao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='id_usuario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='senha_hash', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('MASTER', 'MASTER/MATRIZ'), ('ADMIN', 'ADMIN'), ('GERENTE', 'GERENTE'), ('FUNCIONARIO', 'FUNCIONARIO')], db_column='tipo_usuario', default='FUNCIONARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, db_column='ultimo_login', null=True),
        ),
        migrations.CreateModel(
            name='UsuarioLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_loja', models.ForeignKey(db_column='id_loja', on_delete=django.db.models.deletion.CASCADE, to='lojas.loja')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_loja',
                'unique_together': {('id_usuario', 'id_loja')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='lojas',
            field=models.ManyToManyField(related_name='usuarios', through='usuarios.UsuarioLoja', to='lojas.loja'),
        ),
    ]
