# Generated by Django 5.2.12 on 2026-05-29 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_remove_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioloja',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuarioloja',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
