# Generated by Django 4.2.30 on 2026-05-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('estoque_maximo', models.IntegerField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('id_loja', models.ForeignKey(db_column='id_loja', on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='lojas.loja')),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='produtos.produto')),
            ],
            options={
                'db_table': 'estoque',
                'unique_together': {('id_produto', 'id_loja')},
            },
        ),
    ]
