# Generated by Django 5.2.12 on 2026-06-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('lojas', '0001_initial'),
        ('produtos', '0002_remove_produto_preco_produto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='id_loja',
            field=models.ForeignKey(db_column='id_loja', on_delete=django.db.models.deletion.CASCADE, to='lojas.loja'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='id_produto',
            field=models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
