# Generated by Django 4.2.30 on 2026-05-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id_loja', models.AutoField(db_column='id_loja', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loja',
            },
        ),
    ]
