# Generated by Django 5.2.12 on 2026-06-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('lojas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(db_column='id_venda', primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Concluída', max_length=50)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('loja', models.ForeignKey(db_column='id_loja', on_delete=django.db.models.deletion.DO_NOTHING, to='lojas.loja')),
                ('vendedor', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venda',
                'managed': True,
            },
        ),
    ]
