# Generated by Django 5.2.12 on 2026-05-29 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id_auditoria', models.AutoField(db_column='id_auditoria', primary_key=True, serialize=False)),
                ('acao', models.CharField(blank=True, max_length=100, null=True)),
                ('tabela_afetada', models.CharField(blank=True, max_length=100, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_column='data_hora')),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('tenant_id', models.IntegerField(blank=True, db_column='tenant_id', null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria',
            },
        ),
    ]
